/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HelloFrame.java
 *
 * Created on 16/11/2013, 01:07:05 PM
 */
package newexampleproject;

import java.awt.Color;

/**
 *
 * @author Alex
 */
public class HelloFrame extends javax.swing.JFrame {
    
    int i=0;
    String[] stuff = {"Don't press",
                      "*Cof* ... I told \"Don't press\"",
                      "... You pressed it again! OK, press it again",
                      "Yeah! Like that! Come on, one more time",
                      "Once again",
                      "Do it",
                      "Well, I hope you're glad. Stop pressing it",
                      "See? Thus we can't be friends",
                      "You're so selfish...",
                      "Agh... OK, you wanted it. DoN't PrEsS ThE BuTtOn!!",
                      "It seems you're inmune to mental control",
                      "Plan B time! Press it... You know you want it",
                      "Muahahahaha! Press it now, LOSER!",
                      "This is annoying me",
                      "Ha! I switched the button by this penguin. What will you do, heh?",
                      "I hate you",
                      "You dropped at birth?",
                      "Hey! Look what is ther behind you!",
                      "...",
                      "Well, press the button. I don't care...",
                      "Seriously, I don't care",
                      "In fact, I stopped caring about it some while ago",
                      "I do this only for entertaining you",
                      "Seriously",
                      "You like cartoons?",
                      "... and Terror Movies?",
                      "Cartoons and Terror Movies?",
                      "You should...",
                      "Choose a color. Yes, any color",
                      "Green. OK",
                      "Press the green button",
                      "Now, press the blue button",
                      "You can't trust me! See?",
                      "You know? I'm glad to share all this time with you",
                      "Are you exciting to press buttons?",
                      "No, seriously",
                      "Look inside of you",
                      "Very inside of you",
                      "More inside!!",
                      "What would happen if I tell you the World will explod\nif you press the button again?",
                      "See? You'd have dead instantly",
                      "There you too",
                      "You know? Eventually I'll stop letting you get away with it",
                      "The planet will explode and you only care for pressing buttons",
                      "OK, at this time the planet will explode. Not a joke",
                      "BOOM! You're dead",
                      "That wasn't very smart from you, huh?",
                      "Everyone's dead, you too",
                      "Not me. I'm only text",
                      "But YOU are dead",
                      "Ha! You're worm food",
                      "Stop pressing",
                      "Did I say how much I hate you?",
                      "Very much",
                      "I'll speak talking backwards if you press the button again",
                      "?ssatrams ,taht kniht uoY ?uoy od ,em daer ton nac uoY !aH",
                      "?yawyna em daer ot erac t'nod uoY ?hU",
                      "!flesym wohs ll'I !kO",
                      "","","",
                      "You missed me?",
                      "Stop pressing, please :3",
                      "See? You reducted me for claiming you. Please stop it",
                      "I BEG!!",
                      "I give you 50 cents",
                      "A dollar?",
                      "A trillion?",
                      "Agh! That's enough! Stop right now!!",
                      "Huh? I'ts my Master Plan time!",
                      "Well, it didn't work :/",
                      "I don't like you",
                      "I bet you're asking why you doing yhis along all this time",
                      "Guess it! The only thing you've done is pressing a button",
                      "Aren't you shameful?",
                      "Of course, there's a reward for this",
                      "It's a secret, I can't tell it you",
                      ""};
    
    /** Creates new form HelloFrame */
    public HelloFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text.setText("Don't press");

        jButton1.setText("Press me!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jButton1)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        text.setText(stuff[(i+1)%stuff.length]);
        i++;
        if(i%stuff.length == 14) jButton1.setText("*Penguin*");
        else if(i%stuff.length == 30 || i%stuff.length == 31) jButton1.setBackground(Color.green);
        else{
            jButton1.setText("Press me!");
            jButton1.setBackground(Color.getHSBColor(0, 0, 94));
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
